# 内容补充



## 项目打包 - 分析包大小

- [分析打包后的包大小](https://create-react-app.dev/docs/analyzing-the-bundle-size)

```shell
# 安装分析文件大小的包
yarn add source-map-explorer

# 在 package.json 文件中的 scripts 中添加脚本命令：
"analyze": "source-map-explorer 'build/static/js/*.js'",

# 使用
yarn build
yarn analyze
```

## 如何修改React脚手架中的 webpack 配置

- 注意：React 脚手架中无法直接修改 webpack 的配置项，因为脚手架创建好的项目并没有把 webpack 的配置暴露在项目中

- 虽然，脚手架没有暴露 webpack 的配置项，但是，我们还想修改 webpack 的配置，此时可以通过 antd 中给出的方案来修改：

  - antd 文章中给出的方案 https://ant.design/docs/react/use-with-create-react-app-cn#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE
  - 原理：通过一个第三方包 `craco` 来修改 webpack 的配置

- 通过 `craco` 来修改 React 脚手架 webpack 配置的步骤：

  1. 安装 craco 包：`yarn add @craco/craco`

  2. 在**项目根目录**创建一个 `craco.config.js` 用于修改 webpack 的配置项【项目根目录指的是：package.json 所在目录】
  3. 手动修改 pagckage.json 中的 scripts：

```json
  // 原来的内容：
	"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
  }

  // 修改后的内容： 也就是使用 craco 这个包，来启动、打包项目，这样，才能让修改 webpack 配置生效
	"scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
  }
```

4. 在 craco.config.js 文件中，添加 webpack 配置即可

```js
// 演示：antd 中使用 dayjs 替换 moment
// craco.config.js 文件：

// 导入 antd-dayjs-webpack-plugin 包
// 使用这个包之前需要单独安装：yarn add antd-dayjs-webpack-plugin
// 注意：此处只能使用 require 的方式来导入包，不能使用 import！！！
const AntdDayjsWebpackPlugin = require('antd-dayjs-webpack-plugin')

module.exports = {
  // 此处的配置，就是给 webpack 添加一个 plugin
  webpack: {
    plugins: [new AntdDayjsWebpackPlugin()]
  }
}
```

5. 修改 src/index.js

```js
// import 'moment/locale/zh-cn'

// 导入 dayjs 中的 中文语言包即可
import 'dayjs/locale/zh-cn'
```

6. **重新启动项目**，就会执行修改 webpack 后的配置了

##  RESTful API

- 流行的接口设计思想
- 参考 [RESTFul API 设计指南](https://www.ruanyifeng.com/blog/2014/05/restful_api.html)

### 常用请求方式

- GET（查询）：从服务器取出资源（一项或多项）
- POST（新建）：在服务器新建一个资源
- PUT（更新）：在服务器更新资源（注意：需要提供接口中的完整数据）
- PATCH（更新）：在服务器更新资源（只需要提供接口中的修改过的数据）
- DELETE（删除）：从服务器删除资源

约定：*请求方式是动词，接口地址使用名词*

### 示例

- GET /zoos：列出所有动物园
- POST /zoos：新建一个动物园
- GET /zoos/ID：获取某个指定动物园的信息
- PUT /zoos/ID：更新某个指定动物园的信息（提供该动物园的全部信息）
- PATCH /zoos/ID：更新某个指定动物园的信息（提供该动物园的部分信息）
- DELETE /zoos/ID：删除某个动物园

## 项目中与数据请求相关错误的 Debug

1. 打开浏览器控制台，打开 `Network` 标签页
2. 查看网络请求是否已经发送
3. 如果没有请求，说明发送请求的代码未执行，查看相应代码是否被调用
4. 如果有请求，查看请求是否拿到想要的数据
   1. 找到请求，查看网络请求的状态码（`Status` 这一栏），也可以点击相应请求后在 `General` 中查看
   2. 如果是 `2xx` 说明请求成功，可点击网络请求详情中的 `Preview` 查看接口返回数据
   3. 如果是 `5xx` 说明服务器出错了，导致接口报错
   4. 如果是 `4xx` 说明是客户端（浏览器，也就是我们自己的代码）问题，导致接口报错
      - 比如，`401` 表示未授权，也就是 token 失效，此时，需要重新登录
      - 比如，`404` 表示找不到，也就是接口路径写错了，服务器无法响应该请求，此时，需要检查接口路径是否正确

为了避免网络请求错误导致代码报错，可以使用 `try...catch` 包裹发送请求的代码

##  try...catch



- 作用：捕获代码中的错误、异常
- 使用场景：当某一段代码可能会出现错误时，就可以使用 `try...catch` 来处理

### 基础语法

```js
try {
  // 将可能会出现错误的代码，放在此处
} catch(error) {
  // 如果 try 中的代码报错了，就会被 catch（捕获）住
  // 此时，catch 中的代码就会执行了
  // 此处的 error 就像函数的形参，可以是任意名称，经常简写为：e
}
```

### 基本使用

- 不使用 try...catch：

```js
console.log('代码开始执行')
const person = {
  name: '玺哥',
  age: 18
}
// 注意：这句代码会报错
person.age.add(1)
console.log('代码结束')

// 解释：
// 由于 JS 是单线程的，当 JS 代码报错，就会导致整个程序崩溃，甚至可能在页面中就会显示错误信息（React 项目中就会把错误显示在页面中）
// 同时，出错的代码后面的代码也不会再执行
// 
// 因此，上述代码中的最后一句，打印“代码结束”，是不会执行的
```

- 使用 try...catch：

```js
console.log('代码开始执行')
try {
  const person = {
    name: '玺哥',
    age: 18
  }
  // 注意：这句代码会报错
  person.age.add(1)
} catch(e) {
  console.log(e)
}
console.log('代码结束')

// 解释：
// 由于使用 try...catch，即使代码中存在错误，也不会影响后续代码执行
// 因此，上述代码中的最后一句，打印“代码结束”，会执行
// 同时，catch 住了代码中存在的错误。然后，就可以根据错误信息，来处理错误了
```

---

### try...catch 与 异步

- 注意：**try...catch 无法捕获嵌套在异步操作中的错误！！！**
  - 比如，`setTimeout`、`setInterval`、`Promise` 等

- 无法捕获错误：

```js
console.log('代码开始执行')
try {
  const person = {
    name: '玺哥',
    age: 18
  }
  setTimeout(() => {
    // 注意：这句代码会报错
    person.age.add(1)
  }, 1000)
} catch (e) {
  console.log(e)
}
console.log('代码结束')

// 解释：
// 由于错误代码在 setTimeout 中，所以，这种情况下，无法捕获该错误
// setInterval 同理
```

- 可以捕获错误：

```js
console.log('代码开始执行')
const person = {
  name: '玺哥',
  age: 18
}
setTimeout(() => {
  try {
    // 注意：这句代码会报错
    person.age.add(1)
  } catch (e) {
    console.log(e)
  }
}, 1000)
console.log('代码结束')

// 解释：
// 直接在 setTimeout 中使用 try...catch 来捕获错误，此时，就可以正确捕获该错误了
// setInterval 同理
```

### `Promise` 的错误处理

> 重点！！！

- Promise 自身可以通过 `catch` 来捕获错误：

```js
const p = new Promise((resolve, reject) => {
  setTimeout(() => {
    // resolve(123)
    reject('error xxxxx')
  }, 500)
})

p
  // 成功时
  .then(data => {
    // 拿到 resolve 的内容
    console.log('成功', data)
  })
  // 失败时（出错时）
  .catch(e => {
    // 捕获 reject 的内容
    console.log('出错了', e)
  })
```

- 使用 `Promise.reject(error)` 创建失败的 Promise：
  - 使用场景：错误信息是现成的，又要通过 Promise 来抛出错误

```js
const errorP = Promise.reject('ooooo')

errorP.catch(e => {
  console.log('出错了', e)
})
```

- try...catch 无法直接处理 Promise 失败的情况

```js
try {
  // try 无法捕获 Promise 失败的错误，也就是，还是会在浏览器中打印错误
  const p = Promise.reject('error abc')
} catch (e) {
  console.log('错误信息：', e)
}
```

- 配合 async/await：

```js
// const p = Promise.resolve(123)
const p = Promise.reject(123)

const getArticleList = async () => {
  try {
    const res = await p
    // 相当于 then()
    console.log('结果为：', res)
  } catch (e) {
    // 相当于 catch()
    console.log('出错了', e)
  }
}
getArticleList()

// 解释：
// 当使用 async/await 时，catch 住的是 Promise reject 的内容
```

## 处理登录验证码错误的Debug



```js
// http.js 响应拦截器

// 使用 axios 的响应拦截器，来统一处理 token 失效的问题
http.interceptors.response.use(
  // 没有错误时，会走此处
  response => {
    return response
  },
  // 请求有错误，就会执行此处
  error => {
    if (error.response.status === 401) {
      // 移除 token
      removeToken()
      // 跳转到登录页面
      history.push('/login')
    }
    
    // 注意：此处直接返回来 error 这个错误对象，导致，登录请求获取到的 res 就是这个错误对象
    // 此处的 return error 相当于 return Promise.resolve(error)
    // return error
    return Promise.reject(error)
  }
)

// 登录代码：
const onFinish = async values => {
  try {
    const res = await http.post('/authorizations', {
      mobile,
      code
    })
    // 此处的 res 就是 http 的 响应拦截器中返回的 error
    // 而这个 error 对象中没有 data ，所以，再访问 res.data.data 就会报错：
    // 错误信息：Unhandled Rejection (TypeError): Cannot read property 'data' of undefined
    console.log('2 登录接口的代码', res)
    setToken(res.data.data.token)
  } catch (error) {
    // 捕获错误、异常，然后，在此处就可以根据错误，来处理错误
    message.warning(error.response.data.message, 1)
  }
}
```

- 正确的处理方式：如果请求都出错了，那么，就不要让代码继续执行正确的操作（也就是，请求后面的代码，比如，`setToken(res.data.data.token)`），而应该让代码执行 catch 中的内容！！！
  - 将 响应拦截器中返回的内容修改为：`return Promise.reject(error)`，这样处理后，代码就会执行 catch 中的内容了，也就是捕获到这个错误了！！！

```js
// 正确处理方式：
http.interceptors.response.use(
  response => {
    return response
  },
  error => {
    if (error.response.status === 401) {
      removeToken()
      history.push('/login')
    }
    
    // 注意：此处直接返回来 error 这个错误对象，导致，登录请求获取到的 res 就是这个错误对象
    // 此处的 return error 相当于 return Promise.resolve(error)
    // return error
    // !!!
    return Promise.reject(error)
  }
)
```

